### ISSUE TITLE
Can't build on mac osx

### ISSUE THREAD

**Issue by laurentbartholdi** [potassco/clingcon#53]
I get a strange error message when trying to build on a macbook (osx 10.14, up-to-date homebrew). Note that I had no problem in building the clingo from git.
```
% cmake -G Ninja       -Bbuild/release       -H.       -DCMAKE_BUILD_TYPE=Release       -DCMAKE_INSTALL_PREFIX="${CONDA_PREFIX}"       -DCLINGCON_MANAGE_RPATH=Off       -DPYCLINGCON_USER_INSTALL=Off       -DPYCLINGCON_USE_INSTALL_PREFIX=On       -DCMAKE_INSTALL_LIBDIR=lib
% cmake --build build/release --target install
[1/5] Building CXX object libclingcon/CMakeFiles/libclingcon.dir/src/parsing.cc.o
FAILED: libclingcon/CMakeFiles/libclingcon.dir/src/parsing.cc.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DCLINGCON_BUILD_LIBRARY -Dlibclingcon_EXPORTS -I../../libclingcon -isystem /usr/local/include -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14 -fPIC -fvisibility=hidden -std=gnu++17 -MD -MT libclingcon/CMakeFiles/libclingcon.dir/src/parsing.cc.o -MF libclingcon/CMakeFiles/libclingcon.dir/src/parsing.cc.o.d -o libclingcon/CMakeFiles/libclingcon.dir/src/parsing.cc.o -c ../../libclingcon/src/parsing.cc
In file included from ../../libclingcon/src/parsing.cc:28:
In file included from ../../libclingcon/clingcon/astutil.hh:95:
../../libclingcon/clingcon/astutil_impl.hh:493:32: error: 'get' does not name a template but is followed by template arguments
            vars.emplace(child.get<char const *>(Clingo::ASTv2::Attribute::Name));
                               ^  ~~~~~~~~~~~~~~
/usr/local/include/clingo.hh:3899:22: note: non-template declaration found by name lookup
inline ASTValue AST::get(Attribute attribute) const {
                     ^
In file included from ../../libclingcon/src/parsing.cc:28:
In file included from ../../libclingcon/clingcon/astutil.hh:95:
../../libclingcon/clingcon/astutil_impl.hh:491:9: error: no matching member function for call to 'visit_ast'
    ast.visit_ast([&](Clingo::ASTv2::AST const &child) {
    ~~~~^~~~~~~~~
/usr/local/include/clingo.hh:4015:18: note: candidate function template not viable: 'this' argument has type 'const Clingo::ASTv2::AST', but method is not marked const
inline void AST::visit_ast(Visitor &&visitor) {
                 ^
In file included from ../../libclingcon/src/parsing.cc:28:
In file included from ../../libclingcon/clingcon/astutil.hh:95:
../../libclingcon/clingcon/astutil_impl.hh:499:60: error: no type named 'ASTRef' in namespace 'Clingo::ASTv2'
inline void collect_variables(VarSet &vars, Clingo::ASTv2::ASTRef ast) {
                                            ~~~~~~~~~~~~~~~^
../../libclingcon/src/parsing.cc:76:24: error: 'get' does not name a template but is followed by template arguments
        auto sym = ast.get<Clingo::Symbol>(Attribute::Term);
                       ^  ~~~~~~~~~~~~~~~~
/usr/local/include/clingo.hh:3899:22: note: non-template declaration found by name lookup
inline ASTValue AST::get(Attribute attribute) const {
                     ^
../../libclingcon/src/parsing.cc:80:17: error: 'get' does not name a template but is followed by template arguments
        if (ast.get<int>(Attribute::External) != 0) {
                ^  ~~~~~
/usr/local/include/clingo.hh:3899:22: note: non-template declaration found by name lookup
inline ASTValue AST::get(Attribute attribute) const {
                     ^
../../libclingcon/src/parsing.cc:83:18: error: 'get' does not name a template but is followed by template arguments
        if (!ast.get<ASTVector>(Attribute::Arguments).empty()) {
                 ^  ~~~~~~~~~~~
/usr/local/include/clingo.hh:3899:22: note: non-template declaration found by name lookup
inline ASTValue AST::get(Attribute attribute) const {
                     ^
../../libclingcon/src/parsing.cc:86:32: error: 'get' does not name a template but is followed by template arguments
        auto const *name = ast.get<char const *>(Attribute::Name);
                               ^  ~~~~~~~~~~~~~~
/usr/local/include/clingo.hh:3899:22: note: non-template declaration found by name lookup
inline ASTValue AST::get(Attribute attribute) const {
                     ^
../../libclingcon/src/parsing.cc:97:21: error: 'get' does not name a template but is followed by template arguments
    auto head = ast.get<AST>(Attribute::Head);
                    ^  ~~~~~
/usr/local/include/clingo.hh:3899:22: note: non-template declaration found by name lookup
inline ASTValue AST::get(Attribute attribute) const {
                     ^
../../libclingcon/src/parsing.cc:101:26: error: 'AST' does not refer to a value
    auto atom = head.get<AST>(Attribute::Atom);
                         ^
/usr/local/include/clingo.hh:2461:7: note: declared here
class AST {
      ^
../../libclingcon/src/parsing.cc:105:29: error: expected '(' for function-style cast or type construction
    auto sign = head.get<int>(Attribute::Sign);
                         ~~~^
../../libclingcon/src/parsing.cc:106:30: error: expected '(' for function-style cast or type construction
    auto value = atom.get<int>(Attribute::Value);
                          ~~~^
../../libclingcon/src/parsing.cc:112:21: error: 'get' does not name a template but is followed by template arguments
    auto body = ast.get<ASTVector>(Attribute::Body);
                    ^  ~~~~~~~~~~~
/usr/local/include/clingo.hh:3899:22: note: non-template declaration found by name lookup
inline ASTValue AST::get(Attribute attribute) const {
                     ^
../../libclingcon/src/parsing.cc:115:25: error: 'get' does not name a template but is followed by template arguments
        auto atom = lit.get<AST>(Attribute::Atom);
                        ^  ~~~~~
/usr/local/include/clingo.hh:3899:22: note: non-template declaration found by name lookup
inline ASTValue AST::get(Attribute attribute) const {
                     ^
../../libclingcon/src/parsing.cc:117:32: error: 'AST' does not refer to a value
            if (match(atom.get<AST>(Attribute::Term), "sum", "diff")) {
                               ^
/usr/local/include/clingo.hh:2461:7: note: declared here
class AST {
      ^
../../libclingcon/src/parsing.cc:119:35: error: 'get' does not name a template but is followed by template arguments
                auto ret_bd = ret.get<ASTVector>(Attribute::Body);
                                  ^  ~~~~~~~~~~~
/usr/local/include/clingo.hh:3899:22: note: non-template declaration found by name lookup
inline ASTValue AST::get(Attribute attribute) const {
                     ^
../../libclingcon/src/parsing.cc:122:62: error: expected '(' for function-style cast or type construction
                auto guard = ret_hd.get<Clingo::Optional<AST>>(Attribute::Guard);
                                        ~~~~~~~~~~~~~~~~~~~~~^
../../libclingcon/src/parsing.cc:124:43: error: 'get' does not name a template but is followed by template arguments
                if (static_cast<Sign>(lit.get<int>(Attribute::Sign)) != Sign::Negation) {
                                          ^  ~~~~~
/usr/local/include/clingo.hh:3899:22: note: non-template declaration found by name lookup
inline ASTValue AST::get(Attribute attribute) const {
                     ^
../../libclingcon/src/parsing.cc:125:55: error: expected '(' for function-style cast or type construction
                    auto const *rel = guard->get<char const *>(Attribute::OperatorName);
                                                 ~~~~ ^
../../libclingcon/src/parsing.cc:143:25: error: 'get' does not name a template but is followed by template arguments
        auto term = ast.get<Clingo::Symbol>(Attribute::Term);
                        ^  ~~~~~~~~~~~~~~~~
/usr/local/include/clingo.hh:3899:22: note: non-template declaration found by name lookup
inline ASTValue AST::get(Attribute attribute) const {
                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

Note that I tried to download the precompiled asset clingcon-3.3.0, but it seems to be actually clingo; at least, it won't process any of the examples in the examples subdirectory.

**Comment by rkaminsk** [comment]
clingcon 5 is still under development and there has been no release yet because it only works with the upcoming clingo 5.5 release. If you want to compile clingcon 5, you have to build it against a development version of clingo. Otherwise, you can also install development versions using conda or pip:

- `conda install -c potassco/label/dev clingcon`, or
- `python3 -m pip install --upgrade --user --extra-index-url https://test.pypi.org/simple/ clingcon`

The latter can then be used like clingcon using `python3 -m clingcon`.

Regarding the examples not running with clingcon 3.3, have you tried to use the examples from the corresponding branch?

- https://github.com/potassco/clingcon/tree/clingcon-3/examples

**Comment by laurentbartholdi** [comment]
Thanks for the quick reply! Indeed, the clingon-3/examples work fine, and so does `python3 -m clingcon`.

However, I'm still surprised, in that I cloned the clingo repository, and ran `cmake --build build --target install` in it, with success. The files /usr/local/include/clingo.{h,hh} are the same as in the clone ~/src/clingo/libclingo/clingo.{h,hh}.

**Comment by rkaminsk** [comment]
> However, I'm still surprised, in that I cloned the clingo repository, and ran `cmake --build build --target install` in it, with success. The files /usr/local/include/clingo.{h,hh} are the same as in the clone ~/src/clingo/libclingo/clingo.{h,hh}.

In your error log, the `AST::get<T>` function is missing. I added this function in a commit a couple of weeks after adding the non-template version. Are you sure that you had an up-to-date version? Otherwise, have you checked that your xcode installation is up-to-date, too?

**Comment by laurentbartholdi** [comment]
Yes, I cloned the master branches of clingo and clingcon today. The xcode installation (11.3.1) is the latest that runs of macos 10.14.

I can see get defined in https://github.com/potassco/clingo/blob/master/libclingo/clingo.hh#L2474 but it's not a template. Am I barking at the wrong branch?

**Comment by rkaminsk** [comment]
> Yes, I cloned the master branches of clingo and clingcon today. The xcode installation (11.3.1) is the latest that runs of macos 10.14.
> 
> I can see get defined in https://github.com/potassco/clingo/blob/master/libclingo/clingo.hh#L2474 but it's not a template. Am I barking at the wrong branch?

Yes, it is the wrong branch. Development happens in the wip branch. I periodically update the master whenever I think the wip branch is in a good state. In any case, I update the master now. Closing this now.
